### ISSUE TITLE
Bug issue

### ISSUE THREAD

**Issue by Sinha28Shivam** [Sinha28Shivam/Testing#2]
Please find the relevant bug

**Comment by rohan-r-a-j** [comment]
Issue has been fixed

**Comment by rohan-r-a-j** [comment]
Issue has been fixed permanently

**Comment by Sinha28Shivam** [comment]
Bug is not solved yet

**Comment by rohan-r-a-j** [comment]
Bug is closed, kindly get your eyes checked with a dentist.
